### ISSUE TITLE
Uncaught non-crude-application: Application 'non-crude-application' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"     at l (https://cdnjs.cloudflare.com/ajax/libs/single-spa/4.3.5/system/single-spa.min.js:1:3541)

### ISSUE THREAD

**Issue by pavankumarpachipala** [joeldenning/single-spa-es5-angularjs#3] opened 2020-03-13 07:21 UTC

**Comment by internettrans** [comment] 2020-03-14 02:22
This is a duplicate of #4

**Closed as completed by internettrans** 2020-03-14 02:22 UTC
